services:
  sqlserver:
    container_name: sqlserver
    build: docker/db
    user: root
    ports:
      - 1444:1433
  web:
    container_name: tomcat
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./docker/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./docker/tomcat/conf/context.xml:/tmp/context.xml